# List

In [3]:
l = ['a','b', 1 , 2]
print(l)

['a', 'b', 1, 2]


In [4]:
print(l[0])

a


In [6]:
print(l[1] , l[2])

b 1


In [10]:
print(l[-1],l[-3],l[-4])

2 b a


In [11]:
for i in l:
    print(i)

a
b
1
2


In [13]:
for i,v in enumerate(l):
    print(f"[{i}] = {v}")

[0] = a
[1] = b
[2] = 1
[3] = 2


In [14]:
#update
l[2] = 7
print(l)

['a', 'b', 7, 2]


In [15]:
#add value end of the list
l.append(9)
l.append('c')

In [16]:
print(l)

['a', 'b', 7, 2, 9, 'c']


In [17]:
#add value at specific location (index,value)
l.insert(0,'z')
print(l)


['z', 'a', 'b', 7, 2, 9, 'c']


In [18]:
#remove by value {if same value is present , first one will remove only}
l.remove('c')
print(l)

['z', 'a', 'b', 7, 2, 9]


In [19]:
#remove value by index 
del l[0]

In [20]:
print(l)

['a', 'b', 7, 2, 9]


In [28]:
ll = [
    [1,2,3,4,5],
    ['a','b'],
    ['one','two','three']
]
print(ll)

[[1, 2, 3, 4, 5], ['a', 'b'], ['one', 'two', 'three']]


In [33]:
#ll [2][1]  # 'two'
print(ll [2][1]) # two

two


# Tuple

In [34]:
t = ('a','b',1,2)
print(t)

('a', 'b', 1, 2)


In [35]:
print(type(l),type(t))

<class 'list'> <class 'tuple'>


In [ ]:
# Tuple is immuatable 

# SET

In [36]:
s = {"MBA" , "CSE", "ARCH"}
print(s)

{'ARCH', 'CSE', 'MBA'}


In [37]:
#did not maintained the order
#unique item are stored 

In [38]:
print(type(s))

<class 'set'>


In [39]:
#add value
s.add("EEE")
print(s)

{'ARCH', 'EEE', 'CSE', 'MBA'}


In [40]:
#remove value 
s.remove('MBA')
print(s)

{'ARCH', 'EEE', 'CSE'}


In [41]:
#existing 
"CSE" in s

True

# Map / Hash table / Dictionary

In [42]:
d = {"Sadika": 90 , "Afrin": 92 , "Meen": 94}
print(d)

{'Sadika': 90, 'Afrin': 92, 'Meen': 94}


In [43]:
# key can be any data type such as Tuple but not List
#value can be any data type

In [45]:
print(d['Sadika'])

90


In [46]:
d.get('Afrin')

92

In [47]:
d.keys()

dict_keys(['Sadika', 'Afrin', 'Meen'])

In [48]:
d.values()

dict_values([90, 92, 94])

In [49]:
dd = {'person':2 , 'cat':4 , 'spider':8}

In [54]:
for k in dd:
    print(k)

person
cat
spider


In [52]:
for k in dd:
    v = dd[k]  
    print(f"{k} has {v} legs")

person has 2 legs
cat has 4 legs
spider has 8 legs


In [55]:
for k,v in dd.items():
    print(f"{k} has {v} legs")
    

person has 2 legs
cat has 4 legs
spider has 8 legs


In [56]:
#slicing operator, list 
a = [1,2,3,4,5,6,7,8,9]
print(a[0:3])
# staring value inclucive , end value exclusive

[1, 2, 3]


In [57]:
print(a[2:5])

[3, 4, 5]


In [58]:
print(a[:2])

[1, 2]


In [59]:
print(a[3:])

[4, 5, 6, 7, 8, 9]


In [60]:
print(a[:])

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [61]:
print(a[:-1])

[1, 2, 3, 4, 5, 6, 7, 8]


In [62]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]

In [63]:
for x,y in zip(a,b):
    print(x,y)

1 6
2 7
3 8
4 9
5 10


In [64]:
# copy value from a to b
a = [1,2,3,4,5]
b = []
for i in a:
    b.append(i)
    
print(b)

[1, 2, 3, 4, 5]


In [66]:
# suggested , for above problem , faster

# List comprehension

In [67]:
c = [x for x in a]
print(c)

[1, 2, 3, 4, 5]


In [68]:
sq = [x**2 for x in a]
print(sq)

[1, 4, 9, 16, 25]


In [69]:
sq = [x**2 for x in a if x%2==0]
print(sq)

[4, 16]


In [70]:
d = {(a,a):[a,a**2] for a in range(5)}

In [71]:
print(d)

{(0, 0): [0, 0], (1, 1): [1, 1], (2, 2): [2, 4], (3, 3): [3, 9], (4, 4): [4, 16]}


In [73]:
d[(4,4)]

[4, 16]

In [3]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a.shape)

(5,)


In [4]:
a = np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
a = np.ones((3,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
a = np.full((3,5),9)
print(a)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]
