In [1]:
import numpy as np
a = np.array([1,2,3,4,5]) #rank 1 array : one-d array , only coulumn or only row
print(a.shape)

(5,)


In [2]:
 print(a)

[1 2 3 4 5]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
a[0]=11

In [6]:
 print(a)

[11  2  3  4  5]


In [9]:
b = np.array([
    [1,2,3],
    [4,5,6]
])
print(b)            # rank 2 array , 2 -d array

[[1 2 3]
 [4 5 6]]


In [10]:
print(b.shape) 

(2, 3)


In [11]:
b[1,1]

5

In [13]:
a = np.zeros((5,5))

In [14]:
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
a = np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
a = np.full((5,5),8)

In [17]:
print(a)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [18]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
a = np.random.random((5,5))

In [20]:
print(a)

[[0.8824944  0.05367935 0.11237204 0.63134012 0.46655574]
 [0.38767038 0.5159459  0.03938041 0.32164783 0.43658701]
 [0.29889238 0.18490924 0.12894565 0.83544599 0.23603278]
 [0.90883978 0.7339339  0.03135854 0.81895753 0.50062774]
 [0.9006097  0.00576929 0.1952651  0.07643714 0.21210252]]


In [21]:
a = np.random.randint(0,10,(2,2))
print(a)

[[1 5]
 [8 4]]


In [22]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [24]:
print(b[0,0])

2


In [25]:
b[0,0]=77
print(b)

[[77  3]
 [ 6  7]]


In [26]:
print(a[0,0])

1


In [27]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
r1 = a[1:2 , :] # rank 2 , multiple r / c 
print(r1,r1.shape)

[[5 6 7 8]] (1, 4)


In [30]:
r2 = a[1 , :]
print(r2,r2.shape)

[5 6 7 8] (4,)


In [31]:
c1 = a[:,1]
print(c1,c1.shape)

[ 2  6 10] (3,)


In [32]:
c1 = a[:,1:2]
print(c1,c1.shape)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [33]:
a = np.array([
    [1,2],
    [3,4],
    [5,6]
])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [34]:
print(a[[0,1,2],[0,1,0]])

[1 4 5]


In [35]:
print(a[[0,1,2],[1,0,1]]) 

[2 3 6]


In [36]:
print(a[0,1], a[1,0],a[2,1])

2 3 6


In [37]:
#diff between two is , one returing as a list , another one is returning only element 

In [38]:
print([a[0,1], a[1,0],a[2,1]])

[2, 3, 6]


In [70]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [71]:
b = np.array([0,2,0,1])

In [72]:
print(b)

[0 2 0 1]


In [73]:
c = np.arange(4)
print(c)

[0 1 2 3]


In [74]:
print(a[c,b])

[ 1  7  9 14]


In [75]:
print(a[[0,1,2,3],[0,2,0,1]])

[ 1  7  9 14]


In [76]:
a[c,b] += 100

In [77]:
print(a)

[[101   2   3   4]
 [  5   6 107   8]
 [109  10  11  12]
 [ 13 114  15  16]]


In [58]:
a = np.array([
    [1,2],
    [3,4],
    [5,6]
])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [79]:
print(a)

[[101   2   3   4]
 [  5   6 107   8]
 [109  10  11  12]
 [ 13 114  15  16]]


In [78]:
b = a>10
print(b)

[[ True False False False]
 [False False  True False]
 [ True False  True  True]
 [ True  True  True  True]]


In [80]:
print(type(b))

<class 'numpy.ndarray'>


In [81]:
print(a[b])

[101 107 109  11  12  13 114  15  16]


In [82]:
print(a[a>10])

[101 107 109  11  12  13 114  15  16]


In [87]:
x = np.array([
    [1,2],
    [3,4]
],dtype = np.float64) 
print(x)

[[1. 2.]
 [3. 4.]]


In [88]:
y = np.array([
    [5,6],
    [7,8]
],dtype = np.float64)
print(y)

[[5. 6.]
 [7. 8.]]


In [89]:
print(x+y) #element wise adding
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [90]:
print(x-y) #element wise 
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [91]:
print(x*y) #element wise 
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [92]:
print(x/y) #element wise 
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [110]:
x = np.array ([[1,2],[3,4]])
y = np.array ([[5,6],[7,8]])
u = np.array([9,10])
v = np.array([11,12])

In [99]:
9*11+10*12

219

In [100]:
print(u.dot(v))

219


In [101]:
print(np.dot(u,v))

219


In [113]:
print(x.dot(u))
print(np.dot(x,u))

[29 67]
[29 67]


In [112]:
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [114]:
x = np.array ([
    [1,2],
    [3,4]
])

In [115]:
print(np.sum(x))

10


In [116]:
print(np.sum(x, axis =0)) #column wise sum

[4 6]


In [117]:
print(np.sum(x, axis =1)) # row wise sum

[3 7]


In [118]:
print(x)

[[1 2]
 [3 4]]


In [119]:
x

array([[1, 2],
       [3, 4]])

In [120]:
#array to transpose
x.T

array([[1, 3],
       [2, 4]])

In [121]:
u

array([ 9, 10])

In [122]:
u.T

array([ 9, 10])

In [127]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [128]:
b = np.array([1,0,1,0])

In [129]:
print(b)

[1 0 1 0]


In [130]:
c = np.empty_like(a)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [131]:
for i in range(4):
    c[i,:] = a[i,:] + b

In [132]:
print(c)

[[ 2  2  4  4]
 [ 6  6  8  8]
 [10 10 12 12]
 [14 14 16 16]]


In [133]:
a+b #broadcasting

array([[ 2,  2,  4,  4],
       [ 6,  6,  8,  8],
       [10, 10, 12, 12],
       [14, 14, 16, 16]])

In [ ]:
#home work ==> reshape